// src/renderer/widgets/settings/DuplicatesPanel.tsx
import { useState } from 'preact/hooks'
import { ipc } from '../../lib/ipc'
import { cx } from '../../lib/cx'
import type { DuplicateGroup, DuplicateReason, MergeResult } from '@shared/ipc'
import { MergeView } from '../MergeView'
import { library } from '../../stores/library'
import { usePref } from '../../lib/prefs'
import { isNumberIn } from '@shared/prefs'
import s from './DuplicatesPanel.module.css'

const REASONS: { id: DuplicateReason; label: string; hint: string }[] = [
  { id: 'audio_hash', label: 'Identical audio', hint: 'Byte-identical content' },
  { id: 'mb_recording_id', label: 'MusicBrainz id', hint: 'Same tagged recording' },
  { id: 'tags', label: 'Matching tags', hint: 'Same artist, title and album' },
  { id: 'fuzzy', label: 'Similar', hint: 'Same artist and title, similar length — noisy, needs review' }
]

const MAX_SHOWN = 200

const mmss = (ms: number | null): string => {
  if (ms === null) return '—'
  const sec = Math.round(ms / 1000)
  return `${Math.floor(sec / 60)}:${String(sec % 60).padStart(2, '0')}`
}

export function DuplicatesPanel() {
  const [groups, setGroups] = useState<DuplicateGroup[]>([])
  const [busy, setBusy] = useState(false)
  const [ran, setRan] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [merging, setMerging] = useState<number[] | null>(null)
  const tolerance = usePref('duplicates.toleranceSeconds', 3, isNumberIn(0, 60))

  // Fuzzy is off by default: on a real library it proposes far more than anyone can review.
  const enabled = usePref<Record<DuplicateReason, boolean>>('duplicates.reasons', {
    audio_hash: true, mb_recording_id: true, tags: true, fuzzy: false
  })

  function toggleReason(id: DuplicateReason): void {
    enabled.value = { ...enabled.value, [id]: !enabled.value[id] }
  }

  // Per-group outcome, so a quick merge reports in place rather than reshuffling the list.
  const [done, setDone] = useState<Record<string, MergeResult>>({})
  const [working, setWorking] = useState<Record<string, boolean>>({})
  const [groupError, setGroupError] = useState<Record<string, string>>({})

  /**
   * Merge with the defaults the preview already proposes — richest source survives, multi-value
   * fields union, statistics combine. Safe to offer because it is undoable, and the undo control
   * replaces the button rather than being hidden behind a history view.
   */
  async function quickMerge(g: DuplicateGroup): Promise<void> {
    setWorking((w) => ({ ...w, [g.key]: true }))
    setGroupError((e) => ({ ...e, [g.key]: '' }))
    try {
      const ids = g.members.map((m) => m.trackId)
      const preview = await ipc('tracks:mergePreview', ids)
      const result = await ipc('tracks:merge', { ids, survivor: preview.survivor })
      setDone((d) => ({ ...d, [g.key]: result }))
      await library.refresh()
    } catch (err) {
      setGroupError((e) => ({ ...e, [g.key]: (err as Error).message }))
    } finally {
      setWorking((w) => ({ ...w, [g.key]: false }))
    }
  }

  async function undoGroup(key: string): Promise<void> {
    const r = done[key]
    if (!r) return
    setWorking((w) => ({ ...w, [key]: true }))
    try {
      await ipc('tracks:unmerge', r.batchId)
      setDone((d) => {
        const next = { ...d }
        delete next[key]
        return next
      })
      await library.refresh()
    } catch (err) {
      setGroupError((e) => ({ ...e, [key]: (err as Error).message }))
    } finally {
      setWorking((w) => ({ ...w, [key]: false }))
    }
  }

  async function find(): Promise<void> {
    setBusy(true)
    setError(null)
    try {
      setGroups(await ipc('tracks:duplicates', {
        reasons: REASONS.map((r) => r.id).filter((r) => enabled.value[r]),
        lengthToleranceMs: tolerance.value * 1000,
        limit: MAX_SHOWN
      }))
      setRan(true)
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setBusy(false)
    }
  }

  const total = groups.reduce((n, g) => n + g.members.length, 0)

  return (
    <>
      <section class={s.dupes}>
        <header class={s.header}>
          <h2 class={s.heading}>Find duplicates</h2>
          <p class={s.lead}>
            Anthem never merges automatically. This proposes groups with its reasoning; you decide.
          </p>
        </header>

        <div class={s.opts}>
          {REASONS.map((r) => (
            <label key={r.id} class={s.label} title={r.hint}>
              <input type="checkbox" checked={enabled.value[r.id]} onChange={() => toggleReason(r.id)} />
              {r.label}
              {r.id === 'fuzzy' && <span class={s.warnish}>noisy</span>}
            </label>
          ))}
          <label class={cx(s.label, s.tol)}>
            Length tolerance
            <input type="number" min="0" max="60" value={tolerance.value}
                   onInput={(e) => {
                     const v = (e.currentTarget as HTMLInputElement).value
                     if (v !== '') tolerance.value = +v
                   }} /> s
          </label>
        </div>

        <div class={s.actions}>
          <button class={cx(s.button, s.primary)} onClick={find} disabled={busy}>
            {busy ? 'Searching…' : 'Find duplicates'}
          </button>
          {ran && !busy && (
            <span class={s.hint}>
              {groups.length} group{groups.length === 1 ? '' : 's'} · {total} tracks
              {groups.length >= MAX_SHOWN && <> (showing the first {MAX_SHOWN})</>}
            </span>
          )}
        </div>

        {error && <p class={cx(s.note, s.err)}>{error}</p>}

        {ran && groups.length === 0 && !busy && (
          <p class={s.note}>No duplicates found with these settings.</p>
        )}

        <div class={s.groups}>
          {groups.map((g) => (
            <article key={g.key} class={cx(s.group, s[g.confidence], done[g.key] && s.merged)}>
              <div class={s.ghead}>
                <span class={cx(s.conf, s[g.confidence])}>{g.confidence}</span>
                <span class={s.why}>
                  {done[g.key] ? (
                    `Merged into one track holding ${done[g.key]!.mediaMoved + 1} files.`
                  ) : groupError[g.key] ? (
                    <span class={s.gerr}>{groupError[g.key]}</span>
                  ) : (
                    g.explanation
                  )}
                </span>

                {done[g.key] ? (
                  <button class={cx(s.button, s.undo)} disabled={working[g.key]} onClick={() => undoGroup(g.key)}>
                    {working[g.key] ? 'Undoing…' : 'Undo'}
                  </button>
                ) : (
                  <div class={s.gactions}>
                    <button
                      class={cx(s.button, s.quick)}
                      disabled={working[g.key]}
                      title={'Merge now using the defaults: richest source survives, genres and labels are\ncombined, plays and ratings are combined. Undoable.'}
                      onClick={() => quickMerge(g)}
                    >{working[g.key] ? 'Merging…' : 'Quick merge'}</button>
                    <button class={cx(s.button, s.merge)} onClick={() => setMerging(g.members.map((m) => m.trackId))}>
                      Review
                    </button>
                  </div>
                )}
              </div>
              <table class={s.table}>
                <thead>
                  <tr>
                    <th class={s.th}>Title</th><th class={s.th}>Artist</th><th class={s.th}>Album</th>
                    <th class={cx(s.th, s.num)}>Length</th><th class={cx(s.th, s.num)}>Rating</th>
                    <th class={cx(s.th, s.num)}>Plays</th><th class={cx(s.th, s.num)}>Files</th><th class={s.th}>Formats</th>
                  </tr>
                </thead>
                <tbody class={s.tbody}>
                  {g.members.map((m) => (
                    <tr key={m.trackId}>
                      <td class={s.td}>{m.title ?? '—'}</td>
                      <td class={s.td}>{m.artist ?? '—'}</td>
                      <td class={s.td}>{m.album ?? '—'}</td>
                      <td class={cx(s.td, s.num)}>{mmss(m.lengthMs)}</td>
                      <td class={cx(s.td, s.num)}>{m.rating ?? '—'}</td>
                      <td class={cx(s.td, s.num)}>{m.playCount}</td>
                      <td class={cx(s.td, s.num)}>{m.mediaCount}</td>
                      <td class={s.td}>{m.codecs ?? '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </article>
          ))}
        </div>
      </section>

      {merging && (
        <MergeView
          ids={merging}
          onclose={(merged) => {
            setMerging(null)
            if (merged) {
              void library.refresh()
              void find()
            }
          }}
        />
      )}
    </>
  )
}

// src/renderer/widgets/settings/DuplicatesPanel.svelte
<script lang="ts">
  import { ipc } from '../../lib/ipc'
  import type { DuplicateGroup, DuplicateReason, MergeResult } from '@shared/ipc'
  import MergeView from '../MergeView.svelte'
  import { library } from '../../stores/library.svelte'
  import { pref } from '../../lib/prefs.svelte'
  import { isNumberIn } from '@shared/prefs'

  let groups = $state<DuplicateGroup[]>([])
  let busy = $state(false)
  let ran = $state(false)
  let error = $state<string | null>(null)
  let merging = $state<number[] | null>(null)
  const tolerance = pref('duplicates.toleranceSeconds', 3, isNumberIn(0, 60))

  const REASONS: { id: DuplicateReason; label: string; hint: string }[] = [
    { id: 'audio_hash', label: 'Identical audio', hint: 'Byte-identical content' },
    { id: 'mb_recording_id', label: 'MusicBrainz id', hint: 'Same tagged recording' },
    { id: 'tags', label: 'Matching tags', hint: 'Same artist, title and album' },
    { id: 'fuzzy', label: 'Similar', hint: 'Same artist and title, similar length — noisy, needs review' }
  ]

  // Fuzzy is off by default: on a real library it proposes far more than anyone can review.
  const enabled = pref<Record<DuplicateReason, boolean>>('duplicates.reasons', {
    audio_hash: true, mb_recording_id: true, tags: true, fuzzy: false
  })

  function toggleReason(id: DuplicateReason): void {
    enabled.value = { ...enabled.value, [id]: !enabled.value[id] }
  }

  const MAX_SHOWN = 200

  // Per-group outcome, so a quick merge reports in place rather than reshuffling the list.
  let done = $state<Record<string, MergeResult>>({})
  let working = $state<Record<string, boolean>>({})
  let groupError = $state<Record<string, string>>({})

  /**
   * Merge with the defaults the preview already proposes — richest source survives, multi-value
   * fields union, statistics combine. Safe to offer because it is undoable, and the undo control
   * replaces the button rather than being hidden behind a history view.
   */
  async function quickMerge(g: DuplicateGroup): Promise<void> {
    working = { ...working, [g.key]: true }
    groupError = { ...groupError, [g.key]: '' }
    try {
      const ids = g.members.map((m) => m.trackId)
      const preview = await ipc('tracks:mergePreview', ids)
      const result = await ipc('tracks:merge', { ids, survivor: preview.survivor })
      done = { ...done, [g.key]: result }
      await library.refresh()
    } catch (err) {
      groupError = { ...groupError, [g.key]: (err as Error).message }
    } finally {
      working = { ...working, [g.key]: false }
    }
  }

  async function undoGroup(key: string): Promise<void> {
    const r = done[key]
    if (!r) return
    working = { ...working, [key]: true }
    try {
      await ipc('tracks:unmerge', r.batchId)
      const next = { ...done }
      delete next[key]
      done = next
      await library.refresh()
    } catch (err) {
      groupError = { ...groupError, [key]: (err as Error).message }
    } finally {
      working = { ...working, [key]: false }
    }
  }

  async function find(): Promise<void> {
    busy = true
    error = null
    try {
      groups = await ipc('tracks:duplicates', {
        reasons: REASONS.map((r) => r.id).filter((r) => enabled.value[r]),
        lengthToleranceMs: tolerance.value * 1000,
        limit: MAX_SHOWN
      })
      ran = true
    } catch (err) {
      error = (err as Error).message
    } finally {
      busy = false
    }
  }

  const mmss = (ms: number | null): string => {
    if (ms === null) return '—'
    const s = Math.round(ms / 1000)
    return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`
  }

  const total = $derived(groups.reduce((n, g) => n + g.members.length, 0))
</script>

<section class="dupes">
  <header>
    <h2>Find duplicates</h2>
    <p class="lead">
      Anthem never merges automatically. This proposes groups with its reasoning; you decide.
    </p>
  </header>

  <div class="opts">
    {#each REASONS as r (r.id)}
      <label title={r.hint}>
        <input type="checkbox" checked={enabled.value[r.id]} onchange={() => toggleReason(r.id)} />
        {r.label}
        {#if r.id === 'fuzzy'}<span class="warnish">noisy</span>{/if}
      </label>
    {/each}
    <label class="tol">
      Length tolerance
      <input type="number" min="0" max="60" bind:value={tolerance.value} /> s
    </label>
  </div>

  <div class="actions">
    <button class="primary" onclick={find} disabled={busy}>
      {busy ? 'Searching…' : 'Find duplicates'}
    </button>
    {#if ran && !busy}
      <span class="hint">
        {groups.length} group{groups.length === 1 ? '' : 's'} · {total} tracks
        {#if groups.length >= MAX_SHOWN}(showing the first {MAX_SHOWN}){/if}
      </span>
    {/if}
  </div>

  {#if error}<p class="note err">{error}</p>{/if}

  {#if ran && groups.length === 0 && !busy}
    <p class="note">No duplicates found with these settings.</p>
  {/if}

  <div class="groups">
    {#each groups as g (g.key)}
      <article class="group {g.confidence}" class:merged={done[g.key]}>
        <div class="ghead">
          <span class="conf {g.confidence}">{g.confidence}</span>
          <span class="why">
            {#if done[g.key]}
              Merged into one track holding {done[g.key]!.mediaMoved + 1} files.
            {:else if groupError[g.key]}
              <span class="gerr">{groupError[g.key]}</span>
            {:else}
              {g.explanation}
            {/if}
          </span>

          {#if done[g.key]}
            <button class="undo" disabled={working[g.key]} onclick={() => undoGroup(g.key)}>
              {working[g.key] ? 'Undoing…' : 'Undo'}
            </button>
          {:else}
            <div class="gactions">
              <button
                class="quick"
                disabled={working[g.key]}
                title="Merge now using the defaults: richest source survives, genres and labels are
combined, plays and ratings are combined. Undoable."
                onclick={() => quickMerge(g)}
              >{working[g.key] ? 'Merging…' : 'Quick merge'}</button>
              <button class="merge" onclick={() => (merging = g.members.map((m) => m.trackId))}>
                Review
              </button>
            </div>
          {/if}
        </div>
        <table>
          <thead>
            <tr>
              <th>Title</th><th>Artist</th><th>Album</th>
              <th class="num">Length</th><th class="num">Rating</th>
              <th class="num">Plays</th><th class="num">Files</th><th>Formats</th>
            </tr>
          </thead>
          <tbody>
            {#each g.members as m (m.trackId)}
              <tr>
                <td>{m.title ?? '—'}</td>
                <td>{m.artist ?? '—'}</td>
                <td>{m.album ?? '—'}</td>
                <td class="num">{mmss(m.lengthMs)}</td>
                <td class="num">{m.rating ?? '—'}</td>
                <td class="num">{m.playCount}</td>
                <td class="num">{m.mediaCount}</td>
                <td>{m.codecs ?? '—'}</td>
              </tr>
            {/each}
          </tbody>
        </table>
      </article>
    {/each}
  </div>
</section>

{#if merging}
  <MergeView
    ids={merging}
    onclose={(merged) => {
      merging = null
      if (merged) {
        void library.refresh()
        void find()
      }
    }}
  />
{/if}

<style>
  .dupes { display: grid; gap: var(--space-4); }

  header { display: grid; gap: var(--space-2); }
  h2 { margin: 0; font-size: var(--font-size-lg); color: var(--text-heading); }
  .lead, .hint { margin: 0; font-size: var(--font-size-sm); color: var(--text-tertiary); }

  .opts { display: flex; flex-wrap: wrap; gap: var(--space-4); align-items: center; }
  label { display: flex; gap: var(--space-2); align-items: center; font-size: var(--font-size-sm); }
  .tol input { width: 56px; height: var(--control-height-sm); }

  .warnish {
    padding: 0 var(--space-2);
    font-size: 10px;
    text-transform: uppercase;
    color: var(--status-warning-text);
    background: color-mix(in srgb, var(--status-warning) 16%, transparent);
    border-radius: var(--radius-full);
  }

  .actions { display: flex; gap: var(--space-3); align-items: center; }

  button {
    height: var(--control-height);
    padding: 0 var(--space-4);
    font: inherit;
    color: var(--text-body);
    background: var(--surface-default);
    border: 1px solid var(--border-control);
    border-radius: var(--radius-md);
    cursor: pointer;
  }

  button:disabled { opacity: 0.5; cursor: default; }
  .primary { color: var(--text-on-fill); background: var(--accent); border-color: transparent; }

  .groups { display: grid; gap: var(--space-3); }

  .group {
    border: 1px solid var(--border-default);
    border-radius: var(--radius-md);
    overflow: hidden;
  }

  .ghead {
    display: grid;
    grid-template-columns: auto 1fr auto;
    gap: var(--space-3);
    align-items: center;
    padding: var(--space-2) var(--space-3);
    background: var(--surface-secondary);
    border-bottom: 1px solid var(--border-default);
  }

  .conf {
    padding: 1px var(--space-2);
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    border-radius: var(--radius-full);
    color: var(--text-secondary);
    background: var(--surface-default);
  }

  .conf.certain { color: var(--status-success); background: color-mix(in srgb, var(--status-success) 14%, transparent); }
  .conf.likely { color: var(--accent); background: color-mix(in srgb, var(--accent) 14%, transparent); }
  .conf.possible { color: var(--status-warning-text); background: color-mix(in srgb, var(--status-warning) 16%, transparent); }

  .why { font-size: var(--font-size-sm); color: var(--text-secondary); }
  .gerr { color: var(--status-danger); }

  .gactions { display: flex; gap: var(--space-2); }
  .merge, .quick, .undo { height: var(--control-height-sm); font-size: var(--font-size-sm); }

  .quick {
    color: var(--text-on-fill);
    background: var(--accent);
    border-color: transparent;
  }

  .group.merged { opacity: 0.72; }
  .group.merged table { display: none; }

  table { width: 100%; border-collapse: collapse; font-size: var(--font-size-sm); }
  th { text-align: left; font-weight: 500; color: var(--text-tertiary); }
  th, td { padding: var(--space-1) var(--space-3); }
  td { color: var(--text-body); }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  tbody tr:hover { background: var(--row-hover); }

  .note { margin: 0; font-size: var(--font-size-sm); color: var(--text-tertiary); }
  .note.err { color: var(--status-danger); }
</style>
